### PR TITLE
Bugfix the area in building

### PR DESCRIPTION
**Pull request by spiderbiggen**
Actually put the area inside the building object instead of in an array with the building object

### CODE REVIEW

**Comment by MaxGroenenboom** [comment]
Can't do much wrong here I suppose.

Travis: [Build Status](https://travis-ci.org/spiderbiggen/tygron)

**Comment by klikooo** [comment]
We approve - WSS

**Comment by HarmenKroon** [comment]
We approve as well - CTD

**Comment by MHMCD** [comment]
We approve

\- CodeFox [CodeFox](https://github.com/codefoxnl)

**Pull request merged**
