### PR TITLE
Updated land/3 to land/5 percept.

### PR DESCRIPTION
**Pull request by StefanV7**
Second attempt, let's try it again but with less merge conflicts.

It is now land(`<LandID>`,`<Owner>`,`<MultiPolygon>`,`<ZoneList>`,`<Area>`). #82

### CODE REVIEW

**Comment by Denpeer** [comment]
The tests still aren't here

**Comment by StefanV7** [comment]
There already is a test sellLand

**Comment by MHMCD** [comment]
[Build Status](https://travis-ci.org/levilime/tygron)

We approve

\- CodeFox [CodeFox](https://github.com/codefoxnl)

**Comment by jannelie** [comment]
looks great, we approve -CrashTestDummies

**Comment by nskartoredjo** [comment]
`Land b` still not changed

**Comment by spiderbiggen** [comment]
Looks good I approve 

-RAMpestampers

**Pull request merged**
