### PR TITLE
Context module

### PR DESCRIPTION
**Pull request by spiderbiggen**
This separates our code from code written by wouter, please test if this works for your agent as I only have one agent :+1: 

In your mas2g please remove the domain= setting as this is no longer necessary

### CODE REVIEW

**Comment by klikooo** [comment]
Do you have a travis log?

**Comment by MaxGroenenboom** [comment]
Here it is: https://travis-ci.org/spiderbiggen/tygron/builds/135563756
Looks like some tests are failing.
`Tests in error: 
  testFunctionPercept(tygronenv.TestEnvironmentStates): failed to create project
  testBuildRoadWrongArgs(tygronenv.TestEnvironmentStates): Unexpected exception, expected<eis.exceptions.ActException> but was<eis.exceptions.ManagementException>`
also a single checkstyle error:
`[ERROR] src/main/java/contextvh/login/ContextProjectFactory.java:[9,15] (imports) UnusedImports: Unused import - nl.tytech.core.net.event.IOServiceEventType.GET_MY_STARTABLE_PROJECTS.`

**Comment by spiderbiggen** [comment]
these errors should be fixed now
https://travis-ci.org/spiderbiggen/tygron/builds/135568813

**Comment by MaxGroenenboom** [comment]
Looks nice, the tests succeed now.

**Comment by MaxGroenenboom** [comment]
WhySoSerious approves, tested on our agent and it works (except for the custom action that hasn't been integrated yet)

**Comment by spiderbiggen** [comment]
here is the latest travis build
https://travis-ci.org/spiderbiggen/tygron/builds/135576304

**Comment by nskartoredjo** [comment]
We approve. -CrashTestDummies

**Comment by levilime** [comment]
I verified it's functionality in Goal, it works properly

**Comment by spiderbiggen** [comment]
Just wait a little as I'll go ahead and merge the improvements I asked for.

**Comment by spiderbiggen** [comment]
actually nevermind those changes can be merged later

**Pull request merged**
