### PR TITLE
Requests fix by reemerging it's behaviour over what is added in #50

### LINKED ISSUE #62: Request percept is broken and needs be fixed
From  #50 onward percepts for requests are not brought into the Goal Bot.

### PR DESCRIPTION
**Pull request by levilime**
This fixes #62

### CODE REVIEW

**Comment by klikooo** [comment]
Why are there spaces everywhere?

**Comment by levilime** [comment]
I did not write the code, I used code from 1.0.9 -> #48

**Comment by tvleest** [comment]
approved. /RAMpestampers

**Comment by levilime** [comment]
This can be closed and the fix will propagate through a ticket that expands the request percept.

**Pull request closed without merging**
