### PR TITLE
Fixed the Project Name in the POM.xml

### PR DESCRIPTION
**Pull request by MaxGroenenboom**
Because the Project Name was the same as the Project Name of the environment, it was impossible to import both modules at the same time in eclipse.
Also it doesn't seem logical to have the project name be different from the module name.

### CODE REVIEW

**Comment by spiderbiggen** [comment]
this is not a valid bug as it appends env to the variable name defined earlier in the pom

**Comment by MaxGroenenboom** [comment]
I do think it is a valid bug because when I import the module in Eclipse and choose a project name like `fork - [name]`, it inserts `env` for the name, just like with the old environment. This looks like an oversight in creating the new module.

**Comment by spiderbiggen** [comment]
for me it shows up as contextenv

**Comment by MaxGroenenboom** [comment]
When you import using the name template `fork - [name]` in Advanced? Please try that first.

**Comment by spiderbiggen** [comment]
It then shows up as contextvh

**Comment by spiderbiggen** [comment]
probably because the template doesn't resolve variable names first

**Comment by spiderbiggen** [comment]
If you want to do this please remove the variable and name it contextenv otherwise you will get contextcontextvh if you don't use that template

**Comment by MaxGroenenboom** [comment]
That's strange, for me it creates a project `fork - env`.
I have tried it and I get the project `fork - contextvh`. (after the bugfix)

**Comment by spiderbiggen** [comment]
yea nevermind I see the problem but that's most likely due to eclipse not resolving the variable so please remove the variable and call it contextenv as it's supposed to be called

**Comment by MaxGroenenboom** [comment]
I'm ok with it, I was merely using the same template as the old module uses. In the old module it did say the variable in the name.

**Comment by spiderbiggen** [comment]
I know and that's why it doesn't show up as tygronenv
eclipse doesn't resolve the variable first

**Comment by MaxGroenenboom** [comment]
Ah so it should normally show `tygronenv` and `contextcontextvh` now, too bad about that bug in eclipse then...

**Comment by spiderbiggen** [comment]
looks good to me

\- RAMpestampers

**Comment by jannelie** [comment]
we approve -CrashTestDummies

**Comment by lisv** [comment]
Fine by us.
-CodeFox

**Pull request merged**
