### PR TITLE
Stakeholder percept / WhySoSerious

### PR DESCRIPTION
**Pull request by klikooo**
This addresses issue #10. 

User story: As a virtual human I need to be able to have information on the other stakeholders and myself in the game.

### CODE REVIEW

**Comment by hmyeh** [comment]
Looks good :+1:  - Danshal

**Comment by spiderbiggen** [comment]
Looks good. Although this does mean that if anyone depends on the current implementation they will have to change it, this is not a big problem though - RAMpestampers

**Comment by jannelie** [comment]
Is it possible to test this? - Crash Test Dummies

**Comment by NickTUD** [comment]
@jannelie they did, they changed the test Wouter Pasman implemented

**Comment by jannelie** [comment]
Oh, now I see, looked over it. Then this looks great - Crash Test Dummies

**Pull request merged**
