### PR TITLE
Land/3 is updated to land/5

### PR DESCRIPTION
**Pull request by dionytadema**
The land percept now contains a list of zones it overlaps and it's size in m2

Land(LandID, Stakeholder, Multipolygon, zonelist, area)

### CODE REVIEW

**Comment by klikooo** [comment]
You did not add any tests?

**Comment by dionytadema** [comment]
don't know what happened to the old tests but they seem to have disappeared since #76, i will make an issue to fix this

also this build still fails

**Comment by spiderbiggen** [comment]
I might have accidentaly removed the old lands tests when converting to the module

**Comment by dionytadema** [comment]
if you can make a PR to add them back that would be nice

**Comment by dionytadema** [comment]
I can't seem to fix the null Pointer exeption, and i have other things to do right now, so i will look into the problem tomorow

**Comment by spiderbiggen** [comment]
I can't find the test

**Comment by nskartoredjo** [comment]
We like to see the multi-polygon represented as a list instead of a string (as GOAL has a hard time to parse strings). -CTD

**Comment by nskartoredjo** [comment]
is the area a collection of areas for every polygon in the multi-polygon, or is it the total area of the multi-polygon?

**Comment by tvleest** [comment]
Where do you need a Multipolygon represented as a list for in goal?

**Comment by spiderbiggen** [comment]
@nskartoredjo I believe it is the area of the entire multipolygon,

**EDIT:** just checked it. It is indeed the area of the multipolygons

**Comment by MaxGroenenboom** [comment]
Why would you want multipolygons to be represented as a list? You should do all operations on multipolygons in the connector, goal isn't made for that.

**Comment by nskartoredjo** [comment]
@MaxGroenenboom GOAL shouldn't, but due to the time limitations I like the idea to allow groups to use the multipolygons in GOAL if needed. 

If you want to eliminate the use of multipolygons in GOAL, you could question what the purpose is of percepting land, as most calculations concerning your own land would 
probably be done by custom actions.

**Pull request closed without merging**
