### PR TITLE
Custom actions

### PR DESCRIPTION
**Pull request by MaxGroenenboom**
Added support for custom actions, including an example action, which can be deleted as soon as a real action is implemented.

### CODE REVIEW

**Comment by jannelie** [comment]
I thought Wouter didn't want us to add actions in this way?

**Comment by MaxGroenenboom** [comment]
So, this should go to a new branch if Sander approves that.

**Comment by jannelie** [comment]
So this pull request can be closed I guess?

**Comment by MaxGroenenboom** [comment]
Yeah it can be :)

**Pull request closed without merging**
