### PR TITLE
Update to 1.0.9

### PR DESCRIPTION
**Pull request by MaxGroenenboom**
Almost all conflicts were resolved by Danshal (#43)

Tests were added by WhySoSerious, and some new conflicts were resolved by WhySoSerious.

~~This pull request will definitely fail on Travis, because a lot of the added code is not formatted according to Checkstyle. Apart from these errors, everything else should be fine.
Please review and merge as soon as possible, as this update is very important for future development, and new conflicts can arise at any moment.~~

### CODE REVIEW

**Comment by jannelie** [comment]
In `environment/src/main/java/tygronenv/EisEnv.java` there is a double line `import tygronenv.translators.J2Zone;`  -CrashTestDummies

**Comment by MaxGroenenboom** [comment]
@jannelie Please rather make a new comment instead of editing one, we don't get notifications for edited comments so I wasn't aware your comment was changed :)

**Comment by MaxGroenenboom** [comment]
Please review this well, this large amount of unused imports might indicate errors on my part in the merging process.

**Comment by MHMCD** [comment]
Looks good

\- CodeFox [CodeFox](https://github.com/codefoxnl)

**Comment by MaxGroenenboom** [comment]
I see now that a lot of these warnings I removed were in the master branch of eishub/tygron, so they are not a result of my merging. Fortunately :P

**Comment by spiderbiggen** [comment]
Looks good 

\- RAMpestampers

**Comment by levilime** [comment]
Please wait with the merging of this after I add the behaviour Sander talked about in the contextvh of filtering all changes for checkstyle of active "legacy" coders, Wouter1 and franktygron.

**Comment by MaxGroenenboom** [comment]
@levilime should I pull that from the branch you make that in into this PR? That way we can immediately see it succeed on Travis on our repo.

**Comment by levilime** [comment]
@MaxGroenenboom I will branch from this PR and make the change and then notify you that it's done by making a PR (let's call it PR B) to this branch. In PR B you can check additionalities and functionalities.

**Comment by MaxGroenenboom** [comment]
@levilime Alright ;)

**Comment by MaxGroenenboom** [comment]
@levilime's updates to the checkstyle python script have solved all remaining checkstyle issues. Travis passes now (https://travis-ci.org/Denpeer/tygron/builds/133306190).

**Comment by MatthijsJWH** [comment]
Looks great.

-CodeFox

**Comment by tvleest** [comment]
approved.

-RAMpestampers

**Comment by levilime** [comment]
Can someone verify before the merge of this that the environment created with these changes propogate in working behaviour in GOAL. I for one have not yet had success with this.

**Comment by spiderbiggen** [comment]
@levilime Sure can do or at least try

**Edit 1** : after merging with a branch of the current contextbranch it fails at least two tests. 

`Tests in error: 
  testStateChange(tygronenv.TestEnvironmentStates): failed to edit project:null
  testFunctionPercept(tygronenv.TestEnvironmentStates): Failed to create edit slot to create new project`
**Edit 2** : nevermind running install again made it work o.O

**Comment by MaxGroenenboom** [comment]
@levilime I tried, it works fine, it is not compatible with old versions of the agents though. The stakeholder parameter was changed to stakeholder**s**, with an array of identifiers instead of an identifier, and multipolygons were changed. Probabliy other things changed as well that didn't apply to our agent.

**Comment by levilime** [comment]
@MaxGroenenboom @spiderbiggen good to hear, we have it working here too now

**Comment by klikooo** [comment]
If more people approve this, I can create a pr for my_stakeholder_id!

**Comment by jannelie** [comment]
I approve -CrachTestDummies

**Comment by klikooo** [comment]
@levilime Does danshal approve?

**Comment by levilime** [comment]
Absolutely, but Danshal worked on this PR so it is a little biased :smile:

**Comment by spiderbiggen** [comment]
I approve 

\- Rampestampers

**Pull request merged**
