### PR TITLE
Make CI much faster

### PR DESCRIPTION
**Pull request by levilime**
[Build Status](https://travis-ci.org/levilime/tygron)

By not testing the SDK, or the tygronenv, only the contextvh. Also only run the tests once with cobertura:check, not seperate like before.

### CODE REVIEW

**Comment by MaxGroenenboom** [comment]
Looks like a good improvement, I approve.

**Comment by levilime** [comment]
Also this is the #100 PR, :tada: congrats everyone

**Comment by jannelie** [comment]
We approve -CrashTestDummies

**Comment by jzoon** [comment]
Approved
/RAMpestampers

**Comment by MatthijsJWH** [comment]
Good improvement, we approve.
- CodeFox CodeFox

**Pull request merged**
