### PR TITLE
Make custom indicators return values

### LINKED ISSUE #13: Percept Suggestion: zone_link/4
`zone_link/4 - zone_link(<zoneID>, <indID>, <cur_Val>, <tar_Val>)`

Gives information about the indicators in a zone with their current value and target value.

`<zoneID>` - ID of the zone
`<indID>` - ID of a zone's indicator. 
`<cur_Val>` - Current value for the zone indicator.
`<tar_Val>` - Target value for the zone indicator.

### LINKED ISSUE #39: Target value of percept indicator/3 is always 0.0
When I try to use the indicator/3 percept the 3 value, the target value, always is 0.0.

### LINKED ISSUE #53: Parse Excel EXPLANATION in the connector
This can be used by all indicators to return their current value.

Assigned to @MHMCD and @JoshCode

This is a dependency for #13 

\- CodeFox [CF](http://github.com/CodeFoxNL)

### PR DESCRIPTION
**Pull request by JoshCode**
For this to work, a new section has to be added to the **EXPLANATION_MAQUETTE** cell (usually in cell **B10**) concatenated by `TEXT.CONCATENATE()` or `TEKST.SAMENVOEGEN()`, structured as follows (the newlines after a line may be in the Excel sheet, but they may also be removed. Not meaning the `"\n"`'s by the way, the actual newlines in the code blocks):
### For indicators that have one target for all zones

`<ZONE_ID>` has to be replaced by a numeric zone identifier.
`<SCORE_CELL>` has to be replaced by an Excel cell identifier containing the score for that zone.
The `[...]` indicates that more lines with zone ID's and score cells may follow.

```
"<p hidden>";SCORE_MAQUETTE;"multiN";
"<ZONE_ID>";"\t";<SCORE_CELL>;"\n";
[...]
"</p>"
```

**Example**

```
"<p hidden>";SCORE_MAQUETTE;"multiN";
"0";"\t";I17;"\n";
"1";"\t";I18;"\n";
"2";"\t";I19;"\n";
"3";"\t";I20;"\n";
"4";"\t";I21;"\n";
"5";"\t";I22;"\n";
"6";"\t";I23;"\n";
"7";"\t";I24;"\n";
"8";"\t";I25;"\n";
"9";"\t";I26;"\n";
"10";"\t";I27;"\n";
"11";"\t";I28;"\n";
"12";"\t";I29;"\n";
"</p>"
```
### For indicators that have different targets depending on the zone

Pay attention to the `multiT` instead of `multiN`.

`<ZONE_ID>` has to be replaced by a numeric zone identifier.
`<SCORE_CELL>` has to be replaced by an Excel cell identifier containing the score for that zone.
`<TOTAL_TARGET_CELL>` has to be replaced by an Excel cell identifier containing the target value.
`<TARGET_CELL>` has to be replaced by an Excel cell identifier containing the target value.
The `[...]` indicates that more lines with zone ID's and score cells may follow.

```
"<p hidden>";SCORE_MAQUETTE;"\t";<TOTAL_TARGET_CELL>;"multiT";
"<ZONE_ID>";"\t";<SCORE_CELL>;"\t";<TARGET_CELL>;"\n";
[...]
"</p>"
```

or

```
"<p hidden>";SCORE_MAQUETTE;"\t";<TOTAL_TARGET_CELL>;"multiT";
"<ZONE_ID>";"\t";<TARGET_CELL>;"\n";
[...]
"</p>"
```

In which case the `<TOTAL_TARGET_CELL>` is used as a target for all zones.
**Example**

```
"<p hidden>";SCORE_MAQUETTE;"\t";A1;"multiT";
"0";"\t";I17;"\t";J17;"\n";
"1";"\t";I18;"\t";J18;"\n";
"2";"\t";I19;"\t";J19;"\n";
"3";"\t";I20;"\t";J20;"\n";
"4";"\t";I21;"\t";J21;"\n";
"5";"\t";I22;"\t";J22;"\n";
"6";"\t";I23;"\t";J23;"\n";
"7";"\t";I24;"\t";J24;"\n";
"8";"\t";I25;"\t";J25;"\n";
"9";"\t";I26;"\t";J26;"\n";
"10";"\t";I27;"\t";J27;"\n";
"11";"\t";I28;"\t";J28;"\n";
"12";"\t";I29;"\t";J29;"\n";
"</p>"
```

The indicator-percept #22 is changed in the following way:
`indicator/4 - indicator(<indID>, <currentValue>, <targetValue>, [zone_link])`
`[zone_link]` - A list of 0 or more zone links

 `zone_link/4 - zone_link(<zoneID>, <indID>, <cur_Val>, <tar_Val>)`
As described in #13 

This resolves #13, fixed #39 for custom indicators, resolves #53.

### CODE REVIEW

**Comment by dionytadema** [comment]
DaNSHaL aproves

**Comment by levilime** [comment]
Danshal does not approve yet, we do an additional check in Goal to see if it's functional

**Comment by MHMCD** [comment]
A single tag is added for custom indicators which don't make use of zones.

```
"<p hidden>";SCORE_MAQUETTE;"\t";<TOTAL_TARGET_CELL>;"single";"</p>"
```

In this case an indicator will be percepted by goal as:
`indicator/4 - indicator(<indID>, <currentValue>, <targetValue>, [])`

note that you should not add another ; at the end of the Explanation, my experience is that the Explanation returns empty.

**Comment by NickTUD** [comment]
We have checked it and now Danshal approves.

**Comment by tvleest** [comment]
Will test this tonight before approving.
/RAMpestampers

**Comment by tvleest** [comment]
Tested it and it works. approved.
/RAMpestampers

**Comment by StefanV7** [comment]
So `SCORE_MAQUETTE` is not the name of a cell, but `<TOTAL_TARGET_CELL>` is?

**Comment by tvleest** [comment]
TOTAL_TARGET_CELL has to be replaced by an Excel cell identifier containing the target value.
I replaced SCORE_MAQUETTE with the querry for the current score (for the maquette map), but looks like the cell identifier also works.

**Comment by NickTUD** [comment]
~~We can't seem to get it to work. If someone could help us, that would be great. (Danshal)~~
Resolved, works almost as desired. See comment from @Stefan1de1V below

**Comment by StefanV7** [comment]
It never gives back negative values for current, for one zone I get +0.21 instead of -0.21

**Comment by jannelie** [comment]
We tested it with our indicators and it worked.
So we approve -CrashTestDummies

**Comment by MHMCD** [comment]
https://github.com/eishub/tygron/pull/61#issuecomment-223253390 has been fixed in https://github.com/eishub/tygron/pull/61/commits/64e680e57ca90aead44853a4dbfade5d8b0f9ada.

**Comment by StefanV7** [comment]
It works for us now as well, so Danshal also approves!

**Pull request merged**
