### PR TITLE
Custom actions

### PR DESCRIPTION
**Pull request by MaxGroenenboom**
Added custom actions, along with a temporary example action, which can be deleted as soon as any real action is added.

### CODE REVIEW

**Comment by jannelie** [comment]
We approve -CrashTestDummies

**Comment by dionytadema** [comment]
we approve -DaNSHaL

**Comment by JoshCode** [comment]
Shouldn't context-demoversion be updated to the most recent version of the context branch first? To avoid later merge conflicts.

**Comment by klikooo** [comment]
Can't we just delete this branch since it is not necessary anymore.

**Comment by MaxGroenenboom** [comment]
Yes it can be deleted.

**Pull request closed without merging**
