### PR TITLE
Actionlog percept implemented and powermockito added

### LINKED ISSUE #52: Implement Action Log percept to give change of indicators in response to executing actions.
User story: As a goal agent I want to make educated decisions on which actions to take. Through the action log the indicator changes can be read so that these decisions can be made thoughtfully.

### PR DESCRIPTION
**Pull request by hmyeh**
Fixes #52 and added PowerMockito for testing.

actionlog(`<StakeholderID>`, `<actionDescription>`, `<actionID>`, [[`<indicatorID>`, `<indicatorIncrease>`], ..]) 
Only puts an indicator and its increase in the list if the increase is not equal to 0,0.
Danshal

### CODE REVIEW

**Comment by jannelie** [comment]
We approve -CrashTestDummies

**Comment by shdshdw** [comment]
Shouldn't PowerMockito and the Actionlog be PR'ed seperately? I approve both, but I can image that this doesn't hold for everyone.

**Comment by levilime** [comment]
@shdshdw Powermockito was needed to test this functionality reasonibly, because we have to deliver working and tested code, I don't think they can be seperated

**Comment by tvleest** [comment]
approved. /RAMpestampers

There are\* multiple PR's with powermockito btw.

**Comment by MHMCD** [comment]
Approved

\- CodeFox [CodeFox](https://github.com/codefoxnl)

**Comment by klikooo** [comment]
Do you have a travis build log?

**Comment by levilime** [comment]
Travis commit: https://travis-ci.org/levilime/tygron/builds/134421139

**Comment by MaxGroenenboom** [comment]
Alright, we approve of this PR.

**Pull request merged**
