### PR TITLE
Fix the sdk

### PR DESCRIPTION
**Pull request by klikooo**
This fixes the connector (issue #35), Frank said this should fix the problem.
Also fixed a security issue.

### CODE REVIEW

**Comment by tvleest** [comment]
Did you test it?

**Comment by klikooo** [comment]
Of course, you can test it with this jar file:
[tygronenv-1.0.8-jar-with-dependencies.zip](https://github.com/eishub/tygron/files/277251/tygronenv-1.0.8-jar-with-dependencies.zip)

**Comment by tvleest** [comment]
Yes it works. /RAMpestampers

**Comment by JoshCode** [comment]
Approved, merge ASAP.

\- CodeFox [CF](http://github.com/CodeFoxNL)

**Pull request merged**
