### PR TITLE
Setuptravis/ VH-Danshal

### PR DESCRIPTION
**Pull request by levilime**
Adds the Travis yml file and some changes to the code in login and in the pom to make this repository continously integrated.

The login class is adapted to take into account environment variables that are inputted through maven commands, and if present will use them instead of the login functionality that needs user input. These environment variables are configured through Travis -> Settings -> Environment Variables. Needed are a uservalue for the key: "email", and a passwordvalue for the key: "password".

The latex could not be rendered on the CI, because this is not important to continiously test latex rendering is ommited from the build in CI.

Please close this ticket on this repository if Travis CL won't be used on this repository.

### CODE REVIEW

**Comment by levilime** [comment]
Please close this ticket on this repository if Travis CL won't be used on this repository.

**Comment by levilime** [comment]
Will close because logging in without GUI elements is now implemented in eishub/tygron through wouter

**Comment by Wouter1** [comment]
Yes we discussed this. In short,  we want to avoid config files if possible at all. And the login functionality was covered already by the Login main() function that we needed anyway for manual password entry.

Sorry that we had that functionality not yet implemented when you started your CI.

The travis.yml is just for your build system and seems not in place in the main branch.

Did I miss anything?

**Comment by levilime** [comment]
No sounds good, thanks for the feedback

**Comment by levilime** [comment]
@Wouter1 there is one caveat though, which is that the ServicesManager stores the account data actually on a server, login information cannot be changed without a internet connection. Because of this dependency on an external implementation this method cannot be extended to additional configuration data. It won't be possible to do away with config files, things like which project the environment should connect to need to be still in a external file.

**Comment by Wouter1** [comment]
> things like which project the environment should connect to need to 
> be still in a external file.

No, these should be part of the environment init parameters

Wouter

**Pull request closed without merging**
