### PR TITLE
Enhance upgrade types

### PR DESCRIPTION
**Pull request by spiderbiggen**
Change `upgrade_type(<ID>, <SourceFunctionID>, <TargetFunctionID>)` to `upgrade_type(<ID>, [upgrade_pair(<SourceFunctionID>, <TargetFunctionID>)...])` to support multiple pairs per upgrade

### CODE REVIEW

**Comment by jannelie** [comment]
could you give the link to the travis build?

**Comment by spiderbiggen** [comment]
Yes of course
https://travis-ci.org/spiderbiggen/tygron/builds/134494911

**Comment by MHMCD** [comment]
What will happen if the upgrade_type has no upgrade_pairs? 

\- CodeFox [CodeFox](https://github.com/codefoxnl)

**Comment by spiderbiggen** [comment]
@MHMCD it will do the same as the percept did before, ie it will return `upgrade_type(<ID>)`

**Comment by shdshdw** [comment]
Looks like a good addition to the previous percept, approved. 
- CodeFox [CodeFox](https://github.com/codefoxnl)

**Comment by TomBrunner** [comment]
Looks good indeed, only thing I'm wondering why test 3 is before test 2 in J2UpgradeTypeTest.java,
but we approve

-CrashTestDummies

**Comment by spiderbiggen** [comment]
That's a good question although it doesn't really matter as the junit doesn't run the the test in any specific order

**Comment by NickTUD** [comment]
Looks fine indeed
- Danshal

**Comment by MaxGroenenboom** [comment]
I think it wouldn't be a good idea to merge any code in the connector before the context module has been set up.

**Comment by spiderbiggen** [comment]
@MaxGroenenboom this sounds reasonable. Will test the module today and see if it is ready. Couldn't really do that yesterday as it deleted my maps by accident. My bad.

**Comment by spiderbiggen** [comment]
update with the module

**Pull request closed without merging**
