### PR TITLE
All groups can connect to every project on a specific domain. \ RAMpestampers

### PR DESCRIPTION
**Pull request by spiderbiggen**
Make it possible to connect to all projects on a specified domain.
add `domain = "tudelft"` to your mas2g in the same line as `project = ...`
default implementation is still there so not specifying the domain will only give you access to your own projects

### CODE REVIEW

**Comment by jannelie** [comment]
looks great, has this been tested already? - Crash Test Dummies

**Comment by spiderbiggen** [comment]
well I did manually, will write actual tests shortly

**Comment by spiderbiggen** [comment]
@jannelie I just added a test that confirms I can connect to a project that I myself do not own. specifically the vhproject project. This test might not be indicative for one person in the danshal group as he owns the project.

**Comment by jannelie** [comment]
Okay, Looks great! - Crash Test Dummies

**Comment by MaxGroenenboom** [comment]
Looks good to us - WhySoSerious

**Pull request merged**
