### PR TITLE
Extended buildings percept closes #14 \ Rampestampers

### LINKED ISSUE #14: Percept Suggestion: Building/6
- ID
- Name
- Categories
- Floors
- Stakeholder ID
- Construction Year

### PR DESCRIPTION
**Pull request by spiderbiggen**
this percept will return all buildings in the same way building does while adding some extra numerals.

call `percept(extbuildings(X))` to get the list and then 
each building in the list consists of 6 elements

the elements appear in this order
- object id
- building name
- categories
- number of floors
- Owner Stakeholder ID
- construction year

### CODE REVIEW

**Comment by MaxGroenenboom** [comment]
Why did you include the edit in the readme? I don't suppose that should be in the common branch

**Comment by spiderbiggen** [comment]
that's a good question. although this is an issue with git because this would mean we can't have a different readme for each group :-1: . I will remove it though.

**Comment by NickTUD** [comment]
@spiderbiggen 
- No tests?
- Also, is there a reason you're submitting your travis file?
- Why are you merging this into master and not into context?

**Comment by NickTUD** [comment]
Also, is there a reason you're submitting your travis file?

**Comment by HarmGriffioen** [comment]
Merging is master is a no go, please do not do this

**Pull request closed without merging**
