### PR TITLE
Add zoning notification

### PR DESCRIPTION
**Pull request by levilime**
[Build Status](https://travis-ci.org/levilime/tygron)

This is needed for the Municipality to deny all requests that need the zoning to change.

### CODE REVIEW

**Comment by jannelie** [comment]
We approve -CTD

**Comment by MarcianoJ** [comment]
We approve - WhySoSerious

**Comment by spiderbiggen** [comment]
We Approve

\- RAMpestampers

**Comment by JoshCode** [comment]
Approved.

\- CodeFox [CF](http://github.com/CodeFoxNL)

**Pull request merged**
