### PR TITLE
Travis CI configuration

### PR DESCRIPTION
**Pull request by JoshCode**
Travis CI builds for Ruby by default. This adds a fairly default Travis configuration so that the build succeeds.

Make sure to define the variables `email` and `password` on Travis CI. This is the same Travis configuration used before on the shared context project repository.

It also adds a `slack_token` variable that every group can fill in on Travis itself so that every group can integrate Travis CI into Slack, instead of only one group able to hardcode a token into the configuration file.

:sparkles: - Group CodeFox

### CODE REVIEW

**Comment by levilime** [comment]
My current understanding of the current workflow is that this should be merged on the context branch of this repository on the master. We work together on the context branch, and the master on this repo is something we has to be pulled in the context branch continuosly.

**Comment by levilime** [comment]
Also except for the slack token this travis code is the exact same as Team Danshal wrote last Tuesday, because we are graded by contribution https://github.com/levilime/contextvh/pull/1, a mention of this would be nice.

**Comment by Wouter1** [comment]
> My current understanding of the current workflow is that this should be merged on the context branch of this repository on the master.

Yes, the context branch of the tygron project is where Harm merges the changes that all groups agreed on. 

The master and develop branches are where I and Frank work on. These are the "official" releases. At some point we will merge the context branch back into develop and master.

> We work together on the context branch, and the master on this repo is something we has to be pulled in the context branch continuosly

Yes we recommend that. But if you feel something is really off, please discuss.

**Comment by JoshCode** [comment]
> Also except for the slack token this travis code is the exact same as Team Danshal wrote last Tuesday, because we are graded by contribution levilime/contextvh#1, a mention of this would be nice.

@levilime The configuration was taken from the shared connector. I was unaware who wrote it, so I just mentioned that fact.

> Make sure to define the variables `email` and `password` on Travis CI. This is the same Travis configuration used before on the shared context project repository.

---

> My current understanding of the current workflow is that this should be merged on the context branch of this repository on the master. We work together on the context branch, and the master on this repo is something we has to be pulled in the context branch continuosly.

Indeed, my mistake. I will make a new PR. @levilime @Wouter1

**Pull request closed without merging**
