### PR TITLE
Fixes issue #12 indicator_Link/4 and #8 indicator/3

### PR DESCRIPTION
**Pull request by hmyeh**
Fixes issue #12 and issue #8 
Added the percept for the indicator_Link, but changed the original stakeholder percept into this percept.
Added the percept for the indicator.
Added tests for both translator classes.

### CODE REVIEW

**Comment by klikooo** [comment]
Why did you touch the stakeholder percept? And why is the indicator_link percept located in the J2stakeholder class?

**Comment by hmyeh** [comment]
The stakeholder class is the only class that contains the information of the indicatorweights, which is necessary for the indicator_link percept.

**Comment by hmyeh** [comment]
J2Stakeholder is updated by leaving only the indicatorLink and fixing the corresponding test in TestEnvironmentStates

**Comment by hmyeh** [comment]
Merge conflicts between the Stakeholder percept of WhySoSerious and the indicatorLink percept of Danshal have been solved.

**Pull request merged**
