### PR TITLE
Building percept multipolygon

### PR DESCRIPTION
**Pull request by spiderbiggen**
As a developer
I want to be able to have access to the location of a building
So that i can do something with it.

### CODE REVIEW

**Comment by jannelie** [comment]
We approve -CrashTestDummies

**Comment by spiderbiggen** [comment]
Here is a travis link
https://travis-ci.org/spiderbiggen/tygron/builds/134424721
somehow it fails but looking at it I don't know how :confused: 
nevermind checkstyle

**Comment by MaxGroenenboom** [comment]
@spiderbiggen Looks like checkstyle

**Comment by spiderbiggen** [comment]
yea was also a different branch ...
this is the correct one https://travis-ci.org/spiderbiggen/tygron/builds/134422967

**Comment by dionytadema** [comment]
looks good now, DaNSHaL aproves

**Comment by MHMCD** [comment]
Looks good, we approve.

\- CodeFox [CodeFox](https://github.com/codefoxnl)

**Pull request merged**
