### PR TITLE
Buildingperceptupdate

### PR DESCRIPTION
**Pull request by dionytadema**
user story #45 : as a stakeholder I want to be able to know the function of buildings, as municipality i want to be able to check if we did build an azc.

the building percept will change to **building(Id, Name, OwnerID, ConstructionYear, Categories, FunctionID, Floors)**

### CODE REVIEW

**Comment by MaxGroenenboom** [comment]
You should change the javadoc for the method you changed to reflect the changes. Also why do you expect the amount of floors to be 6 if you set it to 5?
And it fails on travis: https://travis-ci.org/levilime/tygron/builds/133081354

**Comment by dionytadema** [comment]
i changed the java doc, as for the amount of floors you are reading that wrong floors is the sixth parameter so that's why it is parameters.get(6), and on our travis it now succeeds in building https://travis-ci.org/levilime/tygron/builds/133352301

**Comment by MaxGroenenboom** [comment]
I see, I interpreted it wrongly because in the former version the index was equal to the value. I approve ;) - WhySoSerious

**Comment by jannelie** [comment]
We approve -CrashTestDummies

**Pull request merged**
